### ISSUE TITLE
twstats and Python 3.10

### ISSUE THREAD

**Issue by leifeld** [fradeve/twtools#5]
Looks like `twstats` doesn't work with Python 3.10 anymore.

> Traceback (most recent call last):
>   File "/usr/bin/twstats", line 33, in <module>
>     sys.exit(load_entry_point('twtools==0.1', 'console_scripts', 'twstats')())
>   File "/usr/bin/twstats", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/lib/python3.10/site-packages/twtools-0.1-py3.10.egg/twtools/twstats.py", line 31, in <module>
> ImportError: cannot import name 'json_normalize' from 'pandas.io.json' (/usr/lib64/python3.10/site-packages/pandas/io/json/__init__.py)
